const tennisRankings = [
    {
      "rank": 1,
      "name": "Carlos Alcaraz Garfia",
      "country_name": "Spain",
      "country_id": "ESP",
      "points": 6740,
      "bestRank": 1,
      "bestRankDate": "12/09/2022",
      "rankDiff": 3,
      "pointsDiff": 1640,
      "bestPoints": 6740
    },
    {
      "rank": 2,
      "name": "Casper Ruud",
      "country_name": "Norway",
      "country_id": "NOR",
      "points": 5850,
      "bestRank": 2,
      "bestRankDate": "12/09/2022",
      "rankDiff": 5,
      "pointsDiff": 1155,
      "bestPoints": 5850
    },
    {
      "rank": 3,
      "name": "Rafael Nadal",
      "country_name": "Spain",
      "country_id": "ESP",
      "points": 5810,
      "bestRank": 1,
      "bestRankDate": "18/08/2008",
      "rankDiff": 0,
      "pointsDiff": 180,
      "bestPoints": 15390
    },
    {
      "rank": 4,
      "name": "Daniil Medvedev",
      "country_name": "Russian Federation",
      "country_id": "RUS",
      "points": 5065,
      "bestRank": 1,
      "bestRankDate": "28/02/2022",
      "rankDiff": -3,
      "pointsDiff": -1820,
      "bestPoints": 10780
    },
    {
      "rank": 5,
      "name": "Alexander Zverev",
      "country_name": "Germany",
      "country_id": "GER",
      "points": 5040,
      "bestRank": 2,
      "bestRankDate": "13/06/2022",
      "rankDiff": -3,
      "pointsDiff": -720,
      "bestPoints": 8240
    },
    {
      "rank": 6,
      "name": "Stefanos Tsitsipas",
      "country_name": "Greece",
      "country_id": "GRE",
      "points": 4810,
      "bestRank": 3,
      "bestRankDate": "09/08/2021",
      "rankDiff": -1,
      "pointsDiff": -80,
      "bestPoints": 8350
    },
    {
      "rank": 7,
      "name": "Novak Djokovic",
      "country_name": "Serbia",
      "country_id": "SRB",
      "points": 3570,
      "bestRank": 1,
      "bestRankDate": "04/07/2011",
      "rankDiff": -1,
      "pointsDiff": -1200,
      "bestPoints": 16950
    },
    {
      "rank": 8,
      "name": "Cameron Norrie",
      "country_name": "United Kingdom",
      "country_id": "GBR",
      "points": 3550,
      "bestRank": 8,
      "bestRankDate": "12/09/2022",
      "rankDiff": 1,
      "pointsDiff": 135,
      "bestPoints": 3550
    },
    {
      "rank": 9,
      "name": "Andrey Rublev",
      "country_name": "Russian Federation",
      "country_id": "RUS",
      "points": 3390,
      "bestRank": 5,
      "bestRankDate": "13/09/2021",
      "rankDiff": 2,
      "pointsDiff": 270,
      "bestPoints": 6400
    },
    {
      "rank": 10,
      "name": "Hubert Hurkacz",
      "country_name": "Poland",
      "country_id": "POL",
      "points": 3355,
      "bestRank": 9,
      "bestRankDate": "08/11/2021",
      "rankDiff": 0,
      "pointsDiff": 0,
      "bestPoints": 3738
    },
    {
      "rank": 11,
      "name": "Jannik Sinner",
      "country_name": "Italy",
      "country_id": "ITA",
      "points": 3200,
      "bestRank": 9,
      "bestRankDate": "01/11/2021",
      "rankDiff": 2,
      "pointsDiff": 180,
      "bestPoints": 3705
    },
    {
      "rank": 12,
      "name": "Taylor Harry Fritz",
      "country_name": "United States",
      "country_id": "USA",
      "points": 3055,
      "bestRank": 12,
      "bestRankDate": "25/07/2022",
      "rankDiff": 0,
      "pointsDiff": -35,
      "bestPoints": 3090
    },
    {
      "rank": 13,
      "name": "Felix Auger Aliassime",
      "country_name": "Canada",
      "country_id": "CAN",
      "points": 2950,
      "bestRank": 8,
      "bestRankDate": "22/08/2022",
      "rankDiff": -5,
      "pointsDiff": -675,
      "bestPoints": 4018
    },
    {
      "rank": 14,
      "name": "Pablo Carreno Busta",
      "country_name": "Spain",
      "country_id": "ESP",
      "points": 2510,
      "bestRank": 10,
      "bestRankDate": "11/09/2017",
      "rankDiff": 1,
      "pointsDiff": 170,
      "bestPoints": 3325
    },
    {
      "rank": 15,
      "name": "Matteo Berrettini",
      "country_name": "Italy",
      "country_id": "ITA",
      "points": 2360,
      "bestRank": 6,
      "bestRankDate": "31/01/2022",
      "rankDiff": -1,
      "pointsDiff": 0,
      "bestPoints": 5533
    },
    {
      "rank": 16,
      "name": "Marin Cilic",
      "country_name": "Croatia",
      "country_id": "CRO",
      "points": 2345,
      "bestRank": 3,
      "bestRankDate": "29/01/2018",
      "rankDiff": 1,
      "pointsDiff": 170,
      "bestPoints": 5155
    },
    {
      "rank": 17,
      "name": "Diego Sebastian Schwartzman",
      "country_name": "Argentina",
      "country_id": "ARG",
      "points": 2110,
      "bestRank": 8,
      "bestRankDate": "12/10/2020",
      "rankDiff": -1,
      "pointsDiff": -90,
      "bestPoints": 3765
    },
    {
      "rank": 18,
      "name": "Karen Khachanov",
      "country_name": "Russian Federation",
      "country_id": "RUS",
      "points": 1990,
      "bestRank": 8,
      "bestRankDate": "15/07/2019",
      "rankDiff": 13,
      "pointsDiff": 675,
      "bestPoints": 2990
    },
    {
      "rank": 19,
      "name": "Frances Tiafoe",
      "country_name": "United States",
      "country_id": "USA",
      "points": 1940,
      "bestRank": 19,
      "bestRankDate": "12/09/2022",
      "rankDiff": 7,
      "pointsDiff": 540,
      "bestPoints": 1940
    },
    {
      "rank": 20,
      "name": "Nick Kyrgios",
      "country_name": "Australia",
      "country_id": "AUS",
      "points": 1780,
      "bestRank": 13,
      "bestRankDate": "24/10/2016",
      "rankDiff": 5,
      "pointsDiff": 350,
      "bestPoints": 2460
    }
  ]